### ISSUE TITLE
Research Backend Testing Best Practices for Laravel / Inertia SPAs

### ISSUE THREAD

**Issue by WindOfRussia** [CSU-Booking-Platform/application#130]
### Challenge
What problem is this spike centered around?  This spike is to generate more information about this problem and inform future stories

While laravel does ship with phpunit by default there isn't much guidance on how to structure your tests. Everyone has a slightly different idea on how to approach different types of tests (unit, feature, integration). This task exist to find out what the laravel community believes are proper best practices when it comes to tests as well as how (and what) to unit test.  

### Time box
This experiment is limited to 1 day

### Findings
In general, feature tests involve some amount of interaction and setup, at the very minimum, you would seed / create a model or two in order to perform the required tests. When it comes to unit testing, this is typically reserved for pieces of application logic that get extracted out into their own service providers / facades. 

Additionally, Laravel Dusk is the officially supported end-to-end browser testing library. 

- Docs: https://laravel.com/docs/8.x/testing
- Dusk: https://laravel.com/docs/8.x/dusk
- [Laravel Testing Strategies](https://vimeo.com/showcase/7060635/video/394206794)
- [Test Driven Laravel - 2016](https://www.youtube.com/watch?v=MdApmmK71WM)
- [Laravel Testing](https://www.youtube.com/watch?v=5wSWYOtBgA8)
- [TDD Laravel 5](https://www.youtube.com/playlist?list=PLpzy7FIRqpGAbkfdxo1MwOS9xjG3O3z1y)

### Recommendations
- // Prepare // Act // Assert... Prepare your data, perform an action, assert that result is as expected
- Outside in Testing or Acceptance based Testing ( First features, then unit testing with mocks )
- Start with basic Restful HTTP tests for Controllers (ex: `$this->post('/route', ['data'])->assertStatus(200)`)
- Use in memory db, factories and seeders to generate data for your tests
- Unit tests might still rely on a database connection to run as expected (ex: test that a user's last_login_at column is nullable.) 
- To make controllers more unit testables: 
   - use Custom Requests to test form validation.. test rules, assert session errors or [laravel-test-assertions](https://github.com/jasonmccreary/laravel-test-assertions)
   - use Single Action Controllers... __invokable() is bless
   - use Repositories to abstract away models and mock repository methods
- Mocking Strategies (https://laravel.com/docs/8.x/mocking) :
   - Don't mock: Eloquent / DB layer, Response / HTTP layer
   - Mock: events, services, custom app logic, anything that is pulled out of the container. 
   - Facades are automatically mockable, useful for complex business logic kept in service providers
   - Testing external APIs with [Guzzle Mock Handler](https://docs.guzzlephp.org/en/stable/testing.html#mock-handler)
- Data Providers are powerful, sometimes more so than the DB.
- If tests need to look at markup or really interact with a page, use Dusk (ex: complex booking flow)

**Comment by alexstojda** [comment]
Nice work Andrew!
