### ISSUE TITLE
4.5 Class Diagram

### ISSUE THREAD

**Issue by alexstojda** [CSU-Booking-Platform/application#137]

**Comment by EvanDime** [comment]
https://lucid.app/invitations/accept/501e6fc0-ef26-412c-9650-1c122751e1fa
Updating class diagram here. 

Added base models and base controller form laravel

**Comment by EvanDime** [comment]
Basic description of Class Diagram.
https://docs.google.com/document/d/1Ihbw8Wyk2vt3ZtAs2OHb8ahC8HgTIxqoOwICp1zNKOE/edit?usp=sharing

**Comment by EvanDime** [comment]
Based off of feedback, added black boxes to represent controllers and classes not yet changed from generated as well as added descriptions for what they are
