### ISSUE TITLE
7. Defect Tracking Report

### ISSUE THREAD

**Issue by alexstojda** [CSU-Booking-Platform/application#143]

**Comment by Alex-Hayeur** [comment]
Since this is the first sprint and there isn't much functionality coded, the document will include an example of our defect tracking process

**Comment by alexstojda** [comment]
@EvanDime will update https://github.com/CSU-Booking-Platform/application/pull/125#issue-504948124 with a screenshot of the bug

**Comment by Alex-Hayeur** [comment]
The bug reporting process is set up and the table is there. Should be good to close.
I appreciate the formatting changes so that it fits in the final doc better.
