### ISSUE TITLE
8. Code Review report

### ISSUE THREAD

**Issue by alexstojda** [CSU-Booking-Platform/application#144]

**Comment by alexstojda** [comment]
@alecadub Maybe instead of this:  ![image.png](https://images.zenhubusercontent.com/5a7de0804b5806bc2bc656cd/cd81743c-4ecb-4309-a068-26c09d6c0eab)

We could have columns like 
| PR #  |  Title | Brief Description |  
|---|---|---|
|[101](https://github.com/CSU-Booking-Platform/application/pull/101)| #33 & #34 Create Permissions & Roles  | Brief Description |

**Comment by alexstojda** [comment]
Also please add the new PRs closed this weekend!

**Comment by alecadub** [comment]
I like it! We can access both the PR and the issue quickly, I'll make the changes!
