### ISSUE TITLE
Create User Stories for Booking Restrictions

### ISSUE THREAD

**Issue by alexstojda** [CSU-Booking-Platform/application#16]
*Do not assign a story-point value to this task*

### What needs to be done

- Create issues in Github using the `Story` template.
- Create any story required for the stakeholder feature to be implemented. 
- Do not assign any attributes to the issue (Lables, epics, story points, etc. This will be done later) 

### Associated Stakeholder Requirement(s)

- Ensure bookings made fall within appropriate time windows in accordance to booking policies (ex: Mezzanine: -Cannot be booked more than fourteen days ahead of time).
- Keep track and limit the number of reservations a user can submit per calendar, per month, per semester.
- Restrict the time of availability.

### Out of scope
Anything not related to writing stories for user management

**Comment by EvanDime** [comment]
@alecadub I have created an initial idea for these requirements. Can you read over the following issues?
#18 - #19 - #20 - #21 - #22

**Comment by alecadub** [comment]
Hey @EvanDime , read the issues and they all look good !
