### ISSUE TITLE
Create User Stories for Booking Process

### ISSUE THREAD

**Issue by alexstojda** [CSU-Booking-Platform/application#17]
*Do not assign a story-point value to this task*

### What needs to be done

- Create issues in Github using the `Story` template.
- Create any story required for the stakeholder feature to be implemented. 
- Do not assign any attributes to the issue (Labels, epics, story points, etc. This will be done later) 

### Associated Stakeholder Requirement(s)

- Booking requests approval by the appropriate approvers (ex: mezzanine tables and conference rooms will be approved by Yu-Hui and the receptionists, but the lounge and cafeteria has to be approved by Yu-Hui and security).

### Out of scope
Anything not related to writing stories for user management

**Comment by Alex-Hayeur** [comment]
Created the two issues #24 and #25
