### ISSUE TITLE
Acceptance Tests for #43 Delete Roles

### ISSUE THREAD

**Issue by Alex-Hayeur** [CSU-Booking-Platform/application#173]
### User story

#43

### Acceptance criteria checklist

- [x] Administrators can delete roles from the system

![43-admin-deletes-roles.gif](https://images.zenhubusercontent.com/5a7de0804b5806bc2bc656cd/145fc80f-b46a-41ad-9375-99171748dede)

- [x] When a role is deleted, it is disassociated from all of its linked users.

![43-role-delete-user-dissociate.gif](https://images.zenhubusercontent.com/5a7de0804b5806bc2bc656cd/4dbcd280-e8be-4340-962c-3e737935a273)

**Comment by Yu-Hui-Yu** [comment]
Tested and approved.
