### ISSUE TITLE
Acceptance Test for #42 Admin Creates Other Users

### ISSUE THREAD

**Issue by Alex-Hayeur** [CSU-Booking-Platform/application#174]
### User story

#42

### Acceptance criteria checklist

- [x] Administrators can create new users 

![42-admin-create-user-AT.gif](https://images.zenhubusercontent.com/5a7de0804b5806bc2bc656cd/51ece301-46c5-48e6-8d9e-79d235394f40)

- [x] The system returns an error when administrators try to create accounts with duplicate identifiers

![42-create-user-duplicate-email-AT.gif](https://images.zenhubusercontent.com/5a7de0804b5806bc2bc656cd/b051170f-3213-47f7-bd78-101b0e578e1f)

**Comment by Yu-Hui-Yu** [comment]
Tested and approved
