### ISSUE TITLE
Acceptance Tests for #41 Admin Deletes other users

### ISSUE THREAD

**Issue by Alex-Hayeur** [CSU-Booking-Platform/application#175]
### User story

#41

### Acceptance criteria checklist

- [x] Administrators can delete normal users

![delete-user-bug-ac.gif](https://images.zenhubusercontent.com/5a7de0804b5806bc2bc656cd/5ba36c10-e90d-48a7-8c25-37ed83252a5d)

**Comment by Yu-Hui-Yu** [comment]
Tested and approved.
