### ISSUE TITLE
Acceptance Tests for #38 Assign Roles to Users

### ISSUE THREAD

**Issue by Alex-Hayeur** [CSU-Booking-Platform/application#178]
### User story

#38

### Acceptance criteria checklist

- [x] Administrators can associate roles to users
- [x] Administrators can disassociate roles from users

![38-add-and-remove-role-user.gif](https://images.zenhubusercontent.com/5a7de0804b5806bc2bc656cd/e40710ab-675e-4cc1-a4ed-9d26da13e384)

**Comment by Yu-Hui-Yu** [comment]
Tested and approved.
