### ISSUE TITLE
Acceptance Tests for #36 Assign Permissions to Roles

### ISSUE THREAD

**Issue by Alex-Hayeur** [CSU-Booking-Platform/application#180]
### User story

#36

### Acceptance criteria checklist

- [x] Administrators can associate permissions to roles

![36-admin-asign-perms-to-role.gif](https://images.zenhubusercontent.com/5a7de0804b5806bc2bc656cd/a4f94d0e-b34b-4f57-8731-a51b7dfdeeaa)

- [x] Administrators can disassociate permissions from roles

![36-admin-unasign-perms-from-role.gif](https://images.zenhubusercontent.com/5a7de0804b5806bc2bc656cd/9bd0b3bb-39b8-47f9-b1b8-ac9532c79757)

**Comment by Yu-Hui-Yu** [comment]
Tested and approved.
