### ISSUE TITLE
Acceptance Tests for #33 Create Roles

### ISSUE THREAD

**Issue by Alex-Hayeur** [CSU-Booking-Platform/application#183]
### User story

#33

### Acceptance criteria checklist

- [x] Administrators can create new roles in the system

![33-create-new-role.gif](https://images.zenhubusercontent.com/5a7de0804b5806bc2bc656cd/cb9fb4f9-5556-44d0-9502-ccf763736876)

**Comment by Yu-Hui-Yu** [comment]
Tested and approved.
