### ISSUE TITLE
Research Performance and Usability Testing

### ISSUE THREAD

**Issue by alexstojda** [CSU-Booking-Platform/application#200]
### Challenge
How do we effectively run Performance & Usability Testing? Based on the findings, recommend which of the two should be implemented in Release 2.

### Time box
This experiment is limited to 2 days

### Findings
With regards to PHP and Laravel, performance testing is done mainly through use of automatic tools such as [AppOptics](https://www.solarwinds.com/appoptics) for PHP or [Blackfire](https://blackfire.io/docs/integrations/paas/laravel-forge) for Laravel. These tools perform stress-tests of the application to ensure that it can withstand heavy loads. 

As for Usability testing, this is preferably done manually. Usability testing is giving early access to a limited number of users . By providing app access to as many user types as possible, their feedback can be used to find where the app's UI is lacking, where processes are too complicated, or if features are unintuitive/unnecessary/absent.  

### Recommendations
After presenting the solutions found and discussing them with the team, we believe that focusing on usability testing will have a larger benefit on our app for two reasons:

1) Our app will potentially be complex, especially since the prerequisites to book rooms are varied depending on both the room and the event being held. A focus on usability testing will help minimize the confusion users may have by pin-pointing where those confusions are. 

2) The logistic challenges of setting up performance testing through Concordia's servers outweighed the benefits the app would receive, especially since this app would ideally not be used for extended periods at once.

**Comment by Alex-Hayeur** [comment]
Updated issue with my findings and the recommendation the team came to after discussion
