### ISSUE TITLE
Update Users: Fields aren't filled when admin click on "update"

### ISSUE THREAD

**Issue by alecadub** [CSU-Booking-Platform/application#208]
## Expected Behavior

When the admin clicks on update users, fields in the modal (name, email, and permissions) are filled with the current db values.

## Current Behavior

When the admin clicks on update users, fields in the modal (name, email, and permissions) are empty.

![image](https://user-images.githubusercontent.com/39540423/100490605-8a8e6380-30ea-11eb-9f60-23f6372a4793.png)

## Possible Solution

Roles have the correct behavior for this. We can use the same logic and apply it to the users.

## Steps to Reproduce
1. Login as admin
2. Navigate to users page
3. Edit a user
4. Observe bug

## Context (Environment)
I want to update a user, and I don't necessarily know all of his fields.

# Bug Submission Checklist
- [ ] Replication steps
- [ ] Screenshots
- [ ] Tagged commits fixing the bug for traceability
- [ ] Tagged commits updating tests to cover the reported bug	
- [ ] (optional) tagged with “performance” label if performance related

**Comment by jonathanp16** [comment]
Closed and mentioned in #265
