### ISSUE TITLE
Bug in update a room

### ISSUE THREAD

**Issue by jonathanp16** [CSU-Booking-Platform/application#234]
## Expected Behavior
User tries to update a room
User changes a field in the update modal
User submits the form and the room is updated and displayed on the rooms list page

## Current Behavior
User tries to update a room
User changes a field in the update modal
User submits the form and receives a 404 error

## Possible Solution
Add the update route 

## Steps to Reproduce
1. Log in with valid credentials
2. Navigate to the rooms page
3. Select a room from the list below and click on update
4. Change one of the values and submit the form

## Context (Environment)
N/A

# Bug Submission Checklist
- [x] Replication steps
- [ ] Screenshots
- [ ] Tagged commits fixing the bug for traceability
- [ ] Tagged commits updating tests to cover the reported bug	
- [ ] (optional) tagged with “performance” label if performance related

**Comment by alecadub** [comment]
@jonathanp16 I'm not able to reproduce this bug? Seems weird to have a 404 error on the main branch looking at the code and the test for it!

Where did you test that bug from? Was it from the main updated branch or a local one (your old version, or the current feature branch you were working on ?)

We should have a second look at this, it works for me!

**Comment by jonathanp16** [comment]
@alecadub I ran into this on my local branch. I added a field to the room model but the  bug was occurring before that. I believe the issue was the return back() at the end of the update in the controller, so @WindOfRussia and I fixed it and it now should work with my PR. We'll definitely take another look at this

**Comment by jonathanp16** [comment]
Closed and mentioned in #265
