### ISSUE TITLE
Acceptance test for #210 Settings Page

### ISSUE THREAD

**Issue by EvanDime** [CSU-Booking-Platform/application#251]
### User story
As an admin, i can update the applications name.
As an admin, i can update the applications logo. 

#210

### Acceptance Test Checklist

- [x] Using form on the settings page, i am able to upload an image and it appear as the applications logo on all pages. 
- [x] Using form on the settings page, i am able to change the name of the application. (refresh page to see the change take place)

**Comment by Yu-Hui-Yu** [comment]
Tested and accepted
