### ISSUE TITLE
Bookings can be recurring and out of series

### ISSUE THREAD

**Issue by joeyabou** [CSU-Booking-Platform/application#252]
### User story
Bookings can be recurring and out of series
### Narrative
As a user when I create a booking request I have the option to make it reccurring daily, weekly or monthly, while respecting the maximum amount of bookings allowed for the room/resource in question
### Acceptance criteria

| # | Given | When | Then |
|---|-------|------|------|
|1|I am an authenticated user|I book a room recurringly while respecting my bookings amounts|the room is booked recurringly |
|2|I am an authenticated user|I book a room recurringly while going above my allowed booking amounts|the booking requested is denied |
|3|I am an authenticated user|I book a room out of series while respecting my bookings amounts|the room is booked |
|4|I am an authenticated user|I book a room out of series while going above my allowed booking amounts|the booking requested is denied |

**Comment by EvanDime** [comment]
Example scenario: If a user has a maximum of 5 reservations available to them. They make a recurring request on mondays. Do we just make 5 bookings that fit their limit, or do we add a thing that when the first booking is complete, automatically book the next monday available?
