### ISSUE TITLE
As a requestee, I am prompted for additional information when my booking request has certain attributes

### ISSUE THREAD

**Issue by joeyabou** [CSU-Booking-Platform/application#255]
### User story
As a requestee, I am prompted for additional information when my booking request has certain attributes.
### Narrative
Depending on the room, time and other requested resources, the booking form varies and additional verification steps may be required. 

For example, if the event will have alcohol served, the required suplemental information is requested (Will alcohol be sold or served, # of bars, etc).  

When this conditional is triggered, I am prompted for additional input be it text or uploading a pdf file.

### Acceptance criteria

| # | Given | When | Then |
|---|-------|------|------|
|1|I am an authenticated user.|My booking requests requires additional information of certain attributes.|New additional attributes are prompted to be filled out in the form.|
|2|I have a form that contains required additonal attributes.|Validation of these new attributes is made.|The form shows validation status.|

**Comment by EvanDime** [comment]
This will need to cover the possibility of dynamically asking to upload certain files for each sub form.

**Comment by WindOfRussia** [comment]
Frontend: conditional rendering of additional sections : food / alcohol
Backend: additional place to store form answers or files uploaded
