### ISSUE TITLE
Edit a Pending Booking

### ISSUE THREAD

**Issue by jonathanp16** [CSU-Booking-Platform/application#27]
### User story
As a user, I am able to edit a booking before it is approved
### Narrative
As a user, once I submit a booking request, I can edit its details prior to it being approved and finalized
### Out of scope

- Editing a booking after it has been approved
- Notifications

### Acceptance criteria

| # | Given | When | Then |
|---|-------|------|------|
|1|I am a user with a pending room booking|I would like to change the property of my booking|I should have the option to edit the booking|

### UI Mockup
![Edit Booking](https://user-images.githubusercontent.com/31771444/94384292-3843bd00-0110-11eb-9a6d-33da6df7ae9b.PNG)

**Comment by alexstojda** [comment]
Don't forget to add a UI mockup for the form itself :)
