### ISSUE TITLE
Document Story #294, Booking a room requires filling out a form

### ISSUE THREAD

**Issue by WindOfRussia** [CSU-Booking-Platform/application#296]
### What needs to be done
 

- [x] Create a GitHub Issue using the story template
- [x] Write acceptance tests
- [x] Create UI mockups
- [ ] Update documentation & design the feature
- [x] Update description to include all relevant info
- [x] Identify possible blockers in other stories.
- [x] Communicate with the team and ask questions

**Comment by Alex-Hayeur** [comment]
![#294](https://user-images.githubusercontent.com/31771444/104143569-09371b80-538e-11eb-9b45-df0a417c2652.PNG)
