### ISSUE TITLE
Document Story #295, approvers can view and evaluate bookings

### ISSUE THREAD

**Issue by WindOfRussia** [CSU-Booking-Platform/application#297]
### What needs to be done
 

- [x] Create a GitHub Issue using the story template
- [x] Write acceptance tests
- [x] Create UI mockups
- [ ] Update documentation & design the feature
- [x] Update description to include all relevant info
- [x] Identify possible blockers in other stories.
- [x] Communicate with the team and ask questions

**Comment by Alex-Hayeur** [comment]
![#295-1](https://user-images.githubusercontent.com/31771444/104143668-69c65880-538e-11eb-8212-e4e884417975.PNG)
![#295-2](https://user-images.githubusercontent.com/31771444/104143672-6b901c00-538e-11eb-882f-10f302b7d563.PNG)
