### ISSUE TITLE
Jetstream update breaks authentication utility 

### ISSUE THREAD

**Issue by EvanDime** [CSU-Booking-Platform/application#307]
Updating Jestream has caused unforseen problems and now the login page does not seem to load. 
## Expected Behavior

Pulling a fresh build of main should have a working login page. 
## Current Behavior

Page loads without the view and throws errors. 
## Steps to Reproduce

1. Pull main branch
2. Rebuild all assets
3. Open the main page and notice it does not load

## Context (Environment)

# Bug Submission Checklist
- [ ] Replication steps
- [ ] Tagged commits fixing the bug for traceability
- [ ] Tagged commits updating tests to cover the reported bug

**Comment by alexstojda** [comment]
@WindOfRussia needs to prove to me that we need this before he wastes another weekend on this ;)
