### ISSUE TITLE
Acceptance for #255 prompted for additional information when my booking request has certain attributes

### ISSUE THREAD

**Issue by joeyabou** [CSU-Booking-Platform/application#313]
### User story
#255

### Acceptance Test Checklist

- [x] User that books a lounge room has its respective attributes prompted
- [x] User that books a mezzanine room has its respective attributes prompted
- [x] User that books a conference room has its respective attributes prompted

**Comment by Yu-Hui-Yu** [comment]
Tested and accepted.
