### ISSUE TITLE
User updates own account

### ISSUE THREAD

**Issue by joeyabou** [CSU-Booking-Platform/application#32]
### User story
As a user, I am able to update my account.
### Narrative
As a user, I am able to update any of my saved information and to be able to change my credentials. 
### Out of scope
User receiving a notification email that their account was modified.
### Acceptance criteria

| # | Given | When | Then |
|---|-------|------|------|
|1|I am a user|I update my information |Updated information is saved in the system|

### UI Mockup:
![Edit Info](https://user-images.githubusercontent.com/31771444/94384088-b9e71b00-010f-11eb-8d5d-4bdd6c95ce2d.PNG)

**Comment by Alex-Hayeur** [comment]
@alexstojda A couple of questions for this issue:

Users can't update their own account ID correct?
And if a user updates their email address, they'll need to re-validate that email address? (Once we have the registration process complete)

**Comment by alexstojda** [comment]
Yes & Yes

**Comment by Alex-Hayeur** [comment]
On researching, the functionality for this issue is there as part of Laravel (editing email and name is already possible)
Currently adding the ability to see your own role on your profile, which is not part of this issue.
