### ISSUE TITLE
Create Roles

### ISSUE THREAD

**Issue by WindOfRussia** [CSU-Booking-Platform/application#33]
### User story
As an administrator, I am able to create roles.

### Narrative
As an administrator, I want to create roles to encompass a set of permissions so that user access to parts of the application can be controlled.

### Out of scope
The actual assignment of users and permissions to roles.

### Acceptance criteria

| # | Given | When | Then |
|---|-------|------|------|
|1|I am an administrator|I create a role|The system registers a new role|
|2|I am not an administrator|I try to create a role|The system prevents me from creating roles|

**Comment by Alex-Hayeur** [comment]
UI is included in #43
