### ISSUE TITLE
Cannot logout

### ISSUE THREAD

**Issue by EvanDime** [CSU-Booking-Platform/application#332]
Once logged in, the logout button located in the site header on the top right does not do anything. 
## Expected Behavior

While logged in, the logout button will logout the current session and redirect to the login page. 
## Current Behavior

While logged in, the logout button does nothing.
## Steps to Reproduce

1. Login as a user
2. Click the profile on the top right
3. Click logout

## Context (Environment)

Found while looking at each page's ui to see what needs to be updated to match Mockups
![Screen Shot 2021-01-23 at 3.19.33 PM.png](https://images.zenhubusercontent.com/5a8615f54b5806bc2bc72115/32f76ea4-d907-452f-8154-6e774dd74749)
# Bug Submission Checklist
- [x] Replication steps
- [x] Screenshots
- [x] Tagged commits fixing the bug for traceability
- [ ] Tagged commits updating tests to cover the reported bug

**Comment by alexstojda** [comment]
Created https://github.com/CSU-Booking-Platform/application/issues/349 to track the creation of a test to cover this bug.
