### ISSUE TITLE
Update dashboard UI

### ISSUE THREAD

**Issue by EvanDime** [CSU-Booking-Platform/application#334]
Currently, the site has the default dashboard that comes with laravel. We need to update it to match the client's page standards
### What needs to be done
 
Update the dashboard vue so that it either uses one we create or update the default one made by laravel/jetstream.
If changes are drastic, make sure tests are update to match.

**Comment by Alex-Hayeur** [comment]
Focusing on admin/reviewer only. The dashboard should focus on website statistics (such as number of reviews needed by the user etc.)
