### ISSUE TITLE
Assign Permissions to Users

### ISSUE THREAD

**Issue by WindOfRussia** [CSU-Booking-Platform/application#35]
### User story
As a super-admin, I should be able assign permissions (directly) to users.

### Narrative
As a super-admin, I want to attach and detach permissions directly with users, so they can access very specific areas in the application that are not currently covered by roles.

### Out of scope
Writing the permission checks and gates in the application code.

### Acceptance criteria

| # | Given | When | Then |
|---|-------|------|------|
|1|I am an administrator|I try to assign a permission to a valid user|The system associates the permission with this user|
|2|I am not an administrator|I try to assign a permission to a valid user|The system prevents me from associating the permission with this user|
|3|I am not an administrator|I try to assign a permission to an invalid user|The system prevents me from associating the permission with this user|
|4|I am an administrator|I try to detach a permission from a valid user|The system disassociates the permission with this user|
|5|I am not an administrator|I try to detach a permission from a valid user|The system prevents me from disassociating the permission with this user|
|6|I am not an administrator|I try to assign a permission to an invalid user|The system prevents me from disassociating the permission with this user|

**Comment by alexstojda** [comment]
This story will not be implemented at this time as it does not add more value to the product as compared to assign permissions to roles and then to assign roles to users. 

Closing.
