### ISSUE TITLE
Assign Permissions to Roles

### ISSUE THREAD

**Issue by WindOfRussia** [CSU-Booking-Platform/application#36]
### User story
As an administrator, I am able to assign permissions to roles.

### Narrative
As an administrator, I want to attach and detach permissions with roles, such that users with those roles gain access to whole sub-sections of the application and I don't have to assign permissions 1 by 1 to each relevant user.

### Out of scope
Writing the permission checks and gates in the application code.

### Acceptance criteria

| # | Given | When | Then |
|---|-------|------|------|
|1|I am an adminsitrator|I try to assign a permission to role|The system associates the permission with this role|
|2|I am an adminsitrator|I try to detach a permission from a role|The system disassociates the permission from this role|
|3|I am not an adminsitrator|I try to assign a permission to role|The system prevents me from associating the permission with this role|
|4|I am not an adminsitrator|I try to detach a permission from a role|The system prevents me from disassociating the permission with this role|

**Comment by Alex-Hayeur** [comment]
UI is included in #43 as permissions are one of the editable values in roles.
