### ISSUE TITLE
Update backlog tables 

### ISSUE THREAD

**Issue by danseremet** [CSU-Booking-Platform/application#366]
### What needs to be done
Match labels with user story numbers and add new tables for each epic in release 2.

**Comment by Alex-Hayeur** [comment]
Updated all the old story labels to link to their Github issues. Currently adding new tables for issues from release 2 (Sprints 4-6)

**Comment by Alex-Hayeur** [comment]
Backlog tables currently up-to-date as of 01/28. Not closing task as there are still uncompleted issues + burndown charts to add.
