### ISSUE TITLE
Book a Room

### ISSUE THREAD

**Issue by KeeganWoods1** [CSU-Booking-Platform/application#39]
### User story
As a user I am able to reserve a room
### Narrative
As a user I would like to reserve a room at a specific time. For the scope of this issue, assume no approvals are needed to book a room. 
### Out of scope
Limited to simply reserving a room. 
### Acceptance criteria

| # | Given | When | Then |
|---|-------|------|------|
|1|I am user of the system|I wish to book a room|I can book the room if its available|
|2|I am user of the system|I wish to book a room that is already booked|I cannot book the room|

### UI Mockup:
![image](https://user-images.githubusercontent.com/46787494/96355543-9da42180-10b0-11eb-998c-6240cf2bed4a.png)

**Comment by alexstojda** [comment]
TODO: Update Acceptance Criteria issues @Alex-Hayeur

**Comment by alexstojda** [comment]
Pushed to Sprint 5

**Comment by alexstojda** [comment]
@WindOfRussia will assist with finalizing the feature

**Comment by jonathanp16** [comment]
Closed by PR #265
