### ISSUE TITLE
Admin deletes other users

### ISSUE THREAD

**Issue by WindOfRussia** [CSU-Booking-Platform/application#41]
### User story
As an administrator, I am able delete any user.

### Narrative
As an administrator, I want to revoke access to the application from existing accounts that have a lower privileges than my account.

### Out of scope
Manage user permissions, delete my own account, account locks, forcing password resets, etc. 

### Acceptance criteria

| # | Given | When | Then |
|---|-------|------|------|
|1|I am an administrator|I try to remove a normal user|The system confirm my action and removes the user|
|2|I am an administrator|I try to remove a admin user|The system prevents me from removing users that have same or higher privileges than my account|
|3|I am not an administrator|I try to remove any user|The system prevents me from removing users|

**Comment by Alex-Hayeur** [comment]
UI for this is included in #42 for creating users
