### ISSUE TITLE
Admin creates other users

### ISSUE THREAD

**Issue by WindOfRussia** [CSU-Booking-Platform/application#42]
### User story
As an administrator, I am able to create accounts.

### Narrative
As an administrator, I want to create accounts on behalf of other users such that I can set it up (assign roles, etc.) and they receive an email to complete the registration on their own.

### Out of scope
Managing user roles or permissions as well as sending the verification email.

### Acceptance criteria

| # | Given | When | Then |
|---|-------|------|------|
|1|I am an administrator|I try to create a new user|The system creates a new user and sends them an email to complete registration|
|2|I am an administrator|I try to create a user but their identifier already exists|The system prevents me from creating a duplicate account|
|3|I am not an administrator|I try to create user|The system prevents me from creating users|

### UI Mockup: 
![image](https://user-images.githubusercontent.com/46787494/96355717-b7466880-10b2-11eb-91b3-1763301cacff.png)

**Comment by EvanDime** [comment]
@Alex-Hayeur 
i started work on the users can create users issue. 
If you look at my fork and branch you should see it.
I got the create user working, my problems are:
A) When the validation fails, i can't seem to get the errors on the frontend.
