### ISSUE TITLE
Delete Roles

### ISSUE THREAD

**Issue by WindOfRussia** [CSU-Booking-Platform/application#43]
### User story
As an administrator, I am able to delete roles.

### Narrative
As an administrator, I want to delete existing roles, which will also remove said roles from the associated users.

### Out of scope
Managing the permissions covered by the roles.

### Acceptance criteria

| # | Given | When | Then |
|---|-------|------|-------|
|1|I am an administrator|I try to remove a role|The system removes that role and disassociates it from all the linked users|
|2|I am not an administrator|I try to remove a role|The system prevents me from removing that role|

### UI Mockup:
![image](https://user-images.githubusercontent.com/46787494/96355704-836b4300-10b2-11eb-8403-090845c6a69c.png)

**Comment by alexstojda** [comment]
Was implemented in earlier PR
