### ISSUE TITLE
Delete Permissions

### ISSUE THREAD

**Issue by WindOfRussia** [CSU-Booking-Platform/application#44]
### User story
As an administrator, I am able to delete permissions.

### Narrative
As an administrator, I want to delete existing permissions, which will also remove said permissions from the associated roles & users, ensuring that the application areas protected by these permissions are no longer accessible.

### Out of scope
Detaching roles from users, removing references to these permissions from the codebase.

### Acceptance criteria

| # | Given | When | Then |
|---|-------|------|-------|
|1|I am an administrator|I try to remove a permission|The system removes that permissions, disassociates it from all the linked roles & users|
|2|I am not an administrator|I try to remove a permission|The system prevents me from removing that permission|

### UI Mockup: 
![image](https://user-images.githubusercontent.com/46787494/96355388-38036580-10af-11eb-872f-910628482188.png)

**Comment by alexstojda** [comment]
As was discussed, permissions will be hard-coded into the system.
