### ISSUE TITLE
Create a complete README.md with project information

### ISSUE THREAD

**Issue by danseremet** [CSU-Booking-Platform/application#51]
*Do not assign a story-point value to this task*

### What needs to be done
Populate the README.md file to contain information about this repository.
Information includes (but is not limited):
- How to successfully get this project going on our local machines
- Details all (commonly used) commands necessary for starting the web server (or if it's already run by default when the dev container starts, to specify it is) (All of this could have its own relative link to a CONTRIBUTING.md file)
- docker (how to go into a bash terminal into your container for those unfamiliar with it e.g. docker exec -it container-id bash
- docker-compose (maybe?)
- testing
- integration testing
- usage of how development tools are used
- etc.. (as you see fit to provide clear and instructive information to developers working on this project)

**Comment by WindOfRussia** [comment]
I this its better leave readme for basic info. We can start a wiki with self contained pages for docker setups, testing and other relevant info like setting up xdebug.
