### ISSUE TITLE
Create rooms

### ISSUE THREAD

**Issue by alexstojda** [CSU-Booking-Platform/application#53]
### User story

As an administrator, I can create a room. 

### Narrative

Administrators must be able to create rooms in the system. 

- id (int) 
- Friendly name
- Room number (Concordia room number) (string) (838) (string)
- Floor (8) (int)
- Building (H) (string) 

### Out of scope

Adding room capabilities (Projector, smart board, etc) 
Creating linked models (no foreign keys, just regular fields for now) 

### Acceptance criteria

| # | Given | When | Then |
|---|-------|------|------|
|1|I am an adminstrator|I create a new room|it is added to the sytem|
|2|I am not an administrator|I create a new room|it is not added to the system|

### UI Mockup:

![image](https://user-images.githubusercontent.com/46787494/96355361-c62b1c00-10ae-11eb-952c-11236cb8badc.png)

**Comment by Alex-Hayeur** [comment]
The UI for this story is included in #37 for viewing all rooms
