### ISSUE TITLE
Delete rooms

### ISSUE THREAD

**Issue by alexstojda** [CSU-Booking-Platform/application#54]
### User story

As an administrator, I can delete a room and define its availabilities. 

### Narrative

Administrators must be able to delete rooms in the system. 

### Out of scope

Adding room capabilities (Projector, smart board, etc) 

### Acceptance criteria

| # | Given | When | Then |
|---|-------|------|------|
|1|I am an adminstrator|I delete a new room|it is deleted from the sytem|
|2|I am not an administrator|I delete a new room|it is not deleted from the system|

**Comment by Alex-Hayeur** [comment]
The UI for this story is included in #37 for viewing all rooms

**Comment by Alex-Hayeur** [comment]
Functionality is complete, I'm writing the tests which should be done this evening.
