### ISSUE TITLE
Email Notifications 

### ISSUE THREAD

**Issue by alexstojda** [CSU-Booking-Platform/application#56]
### User story

As a user, I want to be able to receive notifications via email as events occur in the system. 

### Narrative

Create the email notification system to be consumed by other parts of the system for sending email notifications to users. 

### Out of scope
The specific notifications themselves

### Acceptance criteria

| # | Given | When | Then |
|---|-------|------|------|
|1|I am a user|An event occurs in the system that user should be aware of|they receive an email notification|

**Comment by Alex-Hayeur** [comment]
No example UI needed for this feature. The main email notifications will be:

1. When an administrator needs to approve a booking
2. When an administrator has requested additional information on a user's booking
3. A reminder that one of a user's bookings is approaching
4. When one of a user's bookings has been confirmed or denied. 

These are necessary notifications that shouldn't be opted out of. So with no notifications settings page, there would be no user-interface in the system to prototype.
