### ISSUE TITLE
When logo is unset (default state), no image is show in the admin setting

### ISSUE THREAD

**Issue by alexstojda** [CSU-Booking-Platform/application#566]
## Expected Behavior
If no image is currently selected as the application logo, either display nothing, or the default jet stream logo. 

## Current Behavior
![image](https://user-images.githubusercontent.com/1353716/113350334-51b80280-9307-11eb-82dd-903ee98f9e04.png)

## Possible Solution
Replace whatever code currently displays an image there with the `<x-application-logo>` component. 

# Bug Submission Checklist
- [ ] Screenshots
- [ ] Tagged commits fixing the bug for traceability
- [ ] Tagged commits updating tests to cover the reported bug

**Comment by danseremet** [comment]
@alexstojda This bug is resolved in https://github.com/CSU-Booking-Platform/application/pull/567
and is working correctly in main. We should close this issue now.
