### ISSUE TITLE
Acceptance Tests for #463 Filter booking request list

### ISSUE THREAD

**Issue by alexstojda** [CSU-Booking-Platform/application#577]
### User story

#463

### Acceptance criteria

| # | Given | When | Then |
|---|-------|------|------|
|1|I am logged in as an admin|I navigate to the bookings list|I can see a list of future pending bookings by default and filter options|
|2|I am logged in as an admin|I change the filter options|the bookings list is updated to reflect my chosen filter options (status/date/assigned user)|

**Comment by Yu-Hui-Yu** [comment]
Accepted
