### ISSUE TITLE
Acceptance Tests for #464 Assign/Re-assign Booking Reviewers

### ISSUE THREAD

**Issue by alexstojda** [CSU-Booking-Platform/application#578]
### User story

#464

### Acceptance criteria

| # | Given | When | Then |
|---|-------|------|------|
|1| I am a reviewer AND a booking is in review| I visit the booking details | I can edit the reviewers for this booking |
|2| I am a reviewer AND a booking is not review| I visit the booking details | I can see but not edit the reviewers for this booking |
|3| I am not a reviewer OR a booking is not review| I visit the booking details | I can see but not edit the reviewers for this booking |

**Comment by Yu-Hui-Yu** [comment]
Accepted
