### ISSUE TITLE
Acceptance Tests for #476 Office 365 SSO

### ISSUE THREAD

**Issue by alexstojda** [CSU-Booking-Platform/application#579]
### User story

#476

### Acceptance criteria

| # | Given | When | Then |
|---|-------|------|------|
|1|I am an administrator | I enter the Office 365 authentication credentials in the admin settings | The system is configured to authenticate users with Office 365 |
|2| I am a user with an Office 365 account in the linked organization AND I have an account in the system | I login using my Office 365 account | The system logins me in to the associated system account|

No automated tests for this test since there is a dependency on an external service (Office 365)

**Comment by cgagnond** [comment]
Everything checks out, thanks for your help, Keegan.
