### ISSUE TITLE
Acceptance Tests for #246 Room Blackout Periods

### ISSUE THREAD

**Issue by alexstojda** [CSU-Booking-Platform/application#581]
### User story

#246

### Acceptance criteria

| # | Given | When | Then |
|---|-------|------|------|
|1|I am an admin logged into the system |I set a room to be unbookable during a set period |That room becomes unbookable during that period|
|2|I am not an admin logged into the system |I set a room to be unbookable during a set period |The room does not receive that blackout period|
|3|A room has a blackout period assigned to it |Any user tries to book the room during that blackout period |The booking fails|
|4|A room has a blackout period assigned to it |Any user tries to book that room outside of that blackout period, and all other criteria are met |The booking succeeds|

**Comment by Yu-Hui-Yu** [comment]
Accepted
