### ISSUE TITLE
Acceptance Test for #247 When a room is selected, show different availabilities

### ISSUE THREAD

**Issue by alexstojda** [CSU-Booking-Platform/application#582]
### User story

#247

### Acceptance Test Checklist

| # | Given | When | Then |
|---|-------|------|------|
|1|I am a user|I make a booking request|I should see current room time restrictions in a table|
|2|I am a user|I make a booking request|I should see the current time period when a room is available/unavailable inside a calendar view|

**Comment by Yu-Hui-Yu** [comment]
Accepted
