### ISSUE TITLE
Acceptance Tests for #248 Restric Access of Users from Rooms

### ISSUE THREAD

**Issue by alexstojda** [CSU-Booking-Platform/application#583]
### User story

#248 

### Acceptance criteria

| # | Given | When | Then |
|---|-------|------|------|
|1|As an admin|when i restrict a type of user for a room|that user can no longer book a room|
|2|As a user|when my role is restricted from booking a room|the user is unable to make a booking request|
|3|As a user|when my role is not restricted from booking a room|the user is able to make a booking request|
|4|As an admin|when updating the restrictions of a room|bookings already made won't be cancelled|

**Comment by Yu-Hui-Yu** [comment]
Accepted
