### ISSUE TITLE
Acceptance Test for #250 Different Time Restrictions per user group

### ISSUE THREAD

**Issue by alexstojda** [CSU-Booking-Platform/application#585]
### User story

#250

### Acceptance criteria

| # | Given | When | Then |
|---|-------|------|------|
|1|I am logged in as an admin |I adjust a room's booking restriction for a specific user group |That relation is saved in the system|
|2|I am logged in as a user with an adjusted booking restriction window for a specific room |I request a booking outside of that room's normal booking window, but inside my adjusted booking window, and all the other booking criteria are met |The booking is created successfully|
|3|I am logged in as a user without an adjusted booking restriction window for a specific room |I request a booking outside of that room's normal booking window, but inside that room's adjusted booking window, and all the other booking criteria are met |The booking is not created|
|4|I am logged in as a user with an adjusted booking restriction window for a specific room |I request a booking outside of that room's normal booking window, but inside my adjusted booking window, but some other booking criteria isn't met |The booking is not created|

**Comment by Yu-Hui-Yu** [comment]
Accepted
