### ISSUE TITLE
Acceptance Tests for #252 Bookings can be recurring and out of series

### ISSUE THREAD

**Issue by alexstojda** [CSU-Booking-Platform/application#586]
### User story

#252

### Acceptance criteria

| # | Given | When | Then |
|---|-------|------|------|
|1|I am an authenticated user|I book a room recurringly while respecting my bookings amounts|the room is booked recurringly |
|2|I am an authenticated user|I book a room recurringly while going above my allowed booking amounts|the booking requested is denied |
|3|I am an authenticated user|I book a room out of series while respecting my bookings amounts|the room is booked |
|4|I am an authenticated user|I book a room out of series while going above my allowed booking amounts|the booking requested is denied |

**Comment by Yu-Hui-Yu** [comment]
Accepted
