### ISSUE TITLE
Acceptance Test for #263 Find rooms based on filters

### ISSUE THREAD

**Issue by alexstojda** [CSU-Booking-Platform/application#587]
### User story

#263

### Acceptance criteria

| # | Given | When | Then |
|---|-------|------|------|
|1|I am a logged in authenticated user|I want to find a resource based on its type, available booking time or booking recurrence availability |I can use the various filters to increase my search accuracy and get better results |

**Comment by Yu-Hui-Yu** [comment]
Accepted
