### ISSUE TITLE
Acceptance test for #426, Edit the yearly academic dates

### ISSUE THREAD

**Issue by alecadub** [CSU-Booking-Platform/application#592]
### User story

#426 

### Acceptance Test Checklist

| # | Given | When | Then |
|---|-------|------|------|
|1|Settings Page|User Edit Fall,Winter,Summer semester|It edits the fall winter and summer semester|
|2|Settings page|User add blackout period for civic holidyas|It creates a blackout period for every room|

**Comment by Yu-Hui-Yu** [comment]
Accepted
