### ISSUE TITLE
Room Table is sticking to Room Create Form

### ISSUE THREAD

**Issue by a-drew** [CSU-Booking-Platform/application#645]
## Expected Behavior

Room Table position should not be affected by expanding / contracting tabs in the Room Create form.

## Current Behavior

<img width="1486" alt="Screen Shot 2021-04-06 at 11 35 13 PM" src="https://user-images.githubusercontent.com/6550234/113811570-744c8000-973a-11eb-9736-b2e3eca2c361.png">

## Steps to Reproduce

1. Visit Rooms page as an admin
2. toggle availabilities or attributes
3. 😕 

## Context (Environment)

# Bug Submission Checklist
- [ ] Replication steps
- [ ] Screenshots
- [ ] Tagged commits fixing the bug for traceability
- [ ] Tagged commits updating tests to cover the reported bug	
- [ ] (optional) tagged with “performance” label if performance related

**Comment by alexstojda** [comment]
Seems to have been fixed, closing.
