### ISSUE TITLE
Automatic merging of minor and patch versions for dependencies pull requests

### ISSUE THREAD

**Issue by danseremet** [CSU-Booking-Platform/application#85]
*Do not assign a story-point value to this task*

### What needs to be done
Example:
https://dependabot.com/blog/automatic-pull-request-merging/

With dependabot:
Instead of always needing to approve the minor and patch version, have it done automatically.
- Preferably with no approval required to make it automatic.

**Comment by alexstojda** [comment]
@danseremet I looked into this and unfortunately it's not possible since we require 2 reviews on every PR.
